### ISSUE TITLE
Fix Testing

### ISSUE THREAD

**Issue by nsoblath** [Electrostatics/pb_solvers#3]

**Comment by intendo** [comment]
The unit test looks like it was getting a default from the compiler at 0.0. 

The new compilers make you specify default values (or call them correctly with a value). I agree that it should be feasible to have the user specify a value if that is what is needed. 

In this case, the test is the user and we just needed to know what the value "should" be. 

@nsoblath set the value to 78.54 and continue doing your great work!

**Comment by nsoblath** [comment]
Got it.  Thanks!

**Comment by intendo** [comment]
Do you know if these tests passed before we started updating things?

**Comment by intendo** [comment]
Actually, I think you want to follow the (Google Test Guidelines)(https://github.com/google/googletest/blob/955c7f837efad184ec63e771c42542d37545eaef/docs/advanced.md#catching-failures)

**Comment by nsoblath** [comment]
I think our two options are:
1. Wrap the individual failing assertions with `EXPECT_NONFATAL_FAILURE()`, or
2. Disable the entire test with the `DISABLE_` prefix.

We can't use `EXPECT_FALSE()` in our case because it expects a C++ statement that returns a boolean as its argument.  I tested it out just in case and it doesn't compile.

The two options I mentioned have slightly different consequences and visibility:

1. Using `EXPECT_NONFATAL_FAILURE()` we're turning the failure of individual assertions into successes.  It's not apparent in the output of running the test that anything is out of the ordinary.  The test `BDUTest.BDrunTimeTermRot` has been failing.  Here's what it looks like when we tell it to expect failure:
    ```
    [----------] 11 tests from BDUTest
    <a bunch of tests that run just fine>
    [ RUN      ] BDUTest.BDrunTimeTermRot
    This is step 0 and polz 1
    My units are Internal. Time: 30
    Molecule #1 radius: 2
    	POSITION: [0, 0, 0]
    	ENERGY: 0
    	FORCE: 0.129826, [5.86943e-10 -0.129826 5.86943e-10]
    	TORQUE: 0.0346495, [0.0245009 3.84308e-17 -0.0245009]
    Molecule #2 radius: 2
    	POSITION: [0, 6, 0]
    	ENERGY: 0
    	FORCE: 0.129826, [-5.86943e-10 0.129826 -5.86943e-10]
    	TORQUE: 0.0346495, [-0.0245009 -3.62958e-17 0.0245009]
    [       OK ] BDUTest.BDrunTimeTermRot (42 ms)
    [----------] 11 tests from BDUTest (226 ms total)
    ```
    And the final printing of results:
    ```
    [==========] 162 tests from 20 test suites ran. (1237 ms total)
    [  PASSED  ] 162 tests.
    ```

2. Using the `DISABLED_` prefix we turn off an entire test, including all of the assertions in the test regardless of whether they pass or fail.  Nothing shows up where the tests run:
    ```
    [----------] 10 tests from BDUTest
    <a bunch of tests that run just fine>
    [----------] 10 tests from BDUTest (182 ms total)
    ```
    But it's apparent in the final printing of results that we've disabled a test:
    ```
    [==========] 161 tests from 20 test suites ran. (1167 ms total)
    [  PASSED  ] 161 tests.

      YOU HAVE 1 DISABLED TEST
    ```
